### PR TITLE
Add docs to cover vector axiom sink changes and migration

### PR DESCRIPTION
**Pull request by darach**
Changes the vector docs to align with changes scheduled for the next vector release, fixing #88
Should not be merged until the next vector release is scheduled!

Signed-off-by: Darach Ennis <darach@gmail.com>

### CODE REVIEW

**Comment by darach** [comment]
@jszwedko Here is the axiom side of the docs change to the vector axiom sink. Any possible improvements from a vector perspective let us know!

**Review by jszwedko — COMMENTED** [review]
Thanks for tagging @darach ! These changes look reasonable to me.

**Comment by manototh** [comment]
@darach Thanks for this PR! Is this ready for my review or is it still a draft?

**Review by manototh — APPROVED** [review]

**Comment by manototh** [comment]
@darach Excellent base, thanks a lot for drawing this up! Good to go from my part. I will also write up a changelog entry on Monday.

**Comment by darach** [comment]
Excellent. As you and @jszwedko are happy, then I'm happy. Happy weekend! 🌞

**Pull request merged**
